DROP TABLE IF EXISTS departamentos;
DROP TABLE IF EXISTS empleados;

CREATE TABLE departamentos (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   descripcion varchar(100) NOT NULL
);

CREATE TABLE empleados (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   fecha_ingreso date DEFAULT NULL,
   nombre varchar(200) NOT NULL,
   salario decimal(10,2) DEFAULT NULL,
   departamento_id BIGINT DEFAULT NULL
);

ALTER TABLE empleados ADD CONSTRAINT FK_empleados_departamentos FOREIGN KEY (departamento_id) REFERENCES departamentos (id);